Add module 1 + module 2
js-tasks-ru/vue-20230120_antreesy-web pull request #1
Opened 2023-01-27 17:35 UTC by Antreesy

Тесты не запускались без `@babel/preset-env`, дополнительно добавил в зависимости
По данным модулям вопросов нет, если есть возможности для оптимизации решенийданных задач - буду рад узнать их!

2023-01-27 17:35 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @ShGKme должен запустить тесты.

2023-01-27 19:51 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-01-27 19:58 UTC, ShGKme requested changes
Требуется двустороннее связывание элементов форм. В остальном всё отлично.

2023-01-27 19:58 UTC, ShGKme commented on 01-basics/01-CounterButtonApp/index.html
> +      <button type="button" @click="count++">{{count}}</button>
У текстовой интерполяции обычно принято добавлять пробелы в скобках: `{{ count }}`

2023-01-27 19:58 UTC, ShGKme commented on 01-basics/02-VueCalculator/index.html
> +          <label><input type="radio" @change="changeOperator" name="operator" value="divide" /> ➗</label>
Состояние элементов в компоненте должно полностью определяться компонентом. Сейчас выбрана ли радиокнопка не зависит от состояния компонента. Требуется привязывать `checked`. Иначе при ререндеринге может возникнуть ситуация, когда на странице выбрана не так радиокнопка, которая выбрана в состоянии приложения. 

Проще всего это делать через директиву двустороннего связывания `v-model`.

2023-01-27 19:58 UTC, ShGKme commented on 01-basics/04-MeetupTitle/index.html
> +        </label>
Аналогично с привязкой выделения радиокнопки.

2023-01-27 19:58 UTC, ShGKme commented
> Тесты не запускались без @babel/preset-env, дополнительно добавил в зависимости

Оу, не заметил. Криво обновился задачник. Спасибо, поправлю!

2023-01-29 18:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-01-29 18:31 UTC, ShGKme approved these changes
Все задачи приняты 👍

2023-01-29 18:31 UTC, merged