Add module 02 tasks
js-tasks-ru/vue-20230120_antreesy-web pull request #2
Opened 2023-02-01 19:53 UTC by Antreesy

По задачам вопросов нет, есть пара предложений:

02-04 / MeetupInfo - возможно, здесь стоит попрактиковать передачу пропсов единым объектом. Неочевидны требуемые на тестах форматы дат (`datetime` и `{{ date}}`), возможно, стоит добавить пояснение или ссылку на MDN в задачнике

02-06 ... 02-07 - слишком большой разрыв по сложности, возможно, также стоит добавить пояснение по асинхронным операциям в материалы или задачник

2023-02-01 19:54 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-01 19:59 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-02-01 20:01 UTC, Antreesy commented
Так, мне интересно, почему в последнем задании на `v-show` падали тесты)
И какую директиву из двух стоит здесь использовать (я подразумевал, что митап нам будет нужен, и поэтому его не стоит убирать из DOM)

2023-02-01 22:10 UTC, ShGKme commented
> Так, мне интересно, почему в последнем задании на `v-show` падали тесты)
> И какую директиву из двух стоит здесь использовать (я подразумевал, что митап нам будет нужен, и поэтому его не стоит убирать из DOM)

Если вопрос про `<MeetupView v-if="meetup" :meetup='meetup' />`, то здесь однозначно можно использовать только `v-if`. Когда у нас нет данных митапа, мы не можем выводить компонент представления митапа. Он не имеет смысла без этих данных, показывать его пользователю не будем, и скорее всего в отсутствии данных в нём будут ошибки в вычислениях из-за обращения к свойствам у `null`, что потребует постоянных проверок и лишних `?.`.

`v-show` нужен, когда требуется скрывать контент, который требуется в DOM, и когда элемент требуется часто скрывать показывать. Именно в тех ситуациях, когда не "разные варианты того, что требуется рендерить", а когда нужно скрыть показать элемент. Например, раскрывающиеся элементы.

2023-02-01 22:20 UTC, ShGKme commented
> 02-04 / MeetupInfo - возможно, здесь стоит попрактиковать передачу пропсов единым объектом.

Обычно удобнее передавать параметры по отдельности, не оборачивая их ещё одним объектом.
Так и передавать удобнее и ближе к HTML 

`<Comp a="a" b="b" />` vs `<Comp params="{ a: a, b: b }" />`

И удобнее типизировать отдельные параметры.

Разве что можно было бы здесь передать целиком объект со всем митапом. Но в этом случае компонент будет зависеть от структуры данных митапа, что иногда хочется избегать (но тут уже дискусионно).


> Неочевидны требуемые на тестах форматы дат (`datetime` и `{{ date}}`), возможно, стоит добавить пояснение или ссылку на MDN в задачнике

Это место было на первом и втором вебинарах (https://github.com/js-tasks-ru/vue3-course-materials/blob/master/02-components/02-page-meetups/components/MeetupCard.js), потому подробно не писал. И из тестов видно Но, наверное, стоит добавить, чтобы было меньше сложностей, спасибо.

> 02-06 ... 02-07 - слишком большой разрыв по сложности, возможно, также стоит добавить пояснение по асинхронным операциям в материалы или задачник

Если это про промисы в целом, то вспоминание асинхронности входит в подготовку к курсу и знания JS

2023-02-01 22:23 UTC, ShGKme requested changes
В `02-components/04-MeetupInfo` лучше избавиться от мутации `$options` и использования `mounted` для начальной инициализации компонента.

Лучше всего перенести вычисление даты в вычисляемые свойства или методы.

Остальные задачи приняты, всё отлично.

2023-02-01 22:23 UTC, ShGKme commented on 02-components/05-MeetupAgenda/components/MeetupAgendaItem.js
> +      // }
Описывать тип объекта с учётом всех полей можно либо через классы, либо через TS.

2023-02-01 22:23 UTC, ShGKme commented on 02-components/04-MeetupInfo/components/MeetupInfo.js
> +  },
`this.$options` нельзя мутировать в экземпляре. `$options` - это объект с описанием компонента. Это общее описание для всех его экземпляров. Его изменение во время работы одного экземпляра будет неприятно отлаживать при переиспользовании компонента. 

`$options` - это именно описание компонента. Максимум, что в нём можно сделать - это добавить свои свойства в описание.

`navigator.language` можно сохранить в опции сразу в самом описании.

2023-02-01 22:23 UTC, ShGKme commented on 02-components/04-MeetupInfo/components/MeetupInfo.js
> +  },
Использование `mounted` здесь тоже не очень корректно. `mounted` срабатывает уже ПОСЛЕ того, как компонент первый раз срендерился и смонтировался на странице. В итоге сначала компонент рендерится с 'en-US' и только после обновления уже будет рендериться с новым значением.

(При этом `this.$options.langOptions = navigator.language;` не приведёт к обновлению, так как описание компонента не реактивно, это не данные компонента).

Для сложной инициализации компонента можно использовать хук `created`. А `mounted` - когда нужна асинхронная инициализация, либо работа с DOM после рендеринга.

2023-02-01 22:23 UTC, ShGKme commented on 02-components/04-MeetupInfo/components/MeetupInfo.js
> +        </time>
Вычисления в шаблоне получаются довольно длинными. Проще их сделать в вычисляемом свойстве (или методе). Это решит и проблему работы с `navigator` в шаблоне.

2023-02-01 22:23 UTC, ShGKme commented on 02-components/07-PageMeetup/components/PageMeetup.js
>        </UiContainer>
Так как всегда выводится только один из этих трёх улов, можно использовать с `v-else-if`. Это сделает микрооптимизацию для Vue, который будет знать, что тут всегда ровно 1 узел, а не любой набор от 0 до 3 узлов.

2023-02-02 16:54 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-02-02 19:04 UTC, ShGKme approved these changes
Все задачи приняты

2023-02-02 19:06 UTC, merged